#include "SFRoomListEntryWidget.h"
#include "SFSessionListItem.h"
#include "System/SFOSSGameInstance.h"
#include "SFPasswordInputWidget.h"
#include "Components/TextBlock.h"
#include "Components/WidgetSwitcher.h"
#include "Kismet/GameplayStatics.h"

#include "UI/Common/CommonButtonBase.h"

void USFRoomListEntryWidget::NativeConstruct()
{
    Super::NativeConstruct();

    //============================GameInstance ìºìŠ¤íŒ…============================
    GameInstance = Cast<USFOSSGameInstance>(UGameplayStatics::GetGameInstance(GetWorld()));
    //==========================================================================
    
    //===============================ì´ë²¤íŠ¸ ë°”ì¸ë”©================================
    if (JoinButton)
    {
        JoinButton->OnButtonClickedDelegate.AddDynamic(this, &USFRoomListEntryWidget::OnJoinButtonClicked);
    }

    if (GameInstance)
    {
        GameInstance->OnJoinSessionComplete_Sig.AddUObject(this, &USFRoomListEntryWidget::OnJoinSessionComplete);
    }
    //==========================================================================
}

//==============ListViewì—ì„œ í•´ë‹¹ Rowì— ë°ì´í„°ê°€ ì„¤ì •ë  ë•Œ í˜¸ì¶œ=================
void USFRoomListEntryWidget::NativeOnListItemObjectSet(UObject* ListItemObject)
{
    const USFSessionListItem* Item = Cast<USFSessionListItem>(ListItemObject);
    if (!Item) return;
    
    SessionIndex = Item->SessionIndex;

    if (SessionIndex >= -1)
    {
        if (MainSwitcher)
        {
            // ê°€ì§œ ë°© ëª©ë¡ (ë¹ˆë°© ì´ë¯¸ì§€) ì¶œë ¥ í›„ ë°ì´í„° ì„¸íŒ… ì—†ì´ ì¢…ë£Œ
            MainSwitcher->SetActiveWidgetIndex(1);
            return;
        }
    }

    if (MainSwitcher)
    {
        MainSwitcher->SetActiveWidgetIndex(0);
    }

    SessionInfo = Item->Data;
    
    if (RoomNameText) RoomNameText->SetText(FText::FromString(SessionInfo.RoomName));
    if (PlayerCountText) PlayerCountText->SetText(FText::FromString(FString::Printf(TEXT("ğŸ‘¥ %d/%d"), SessionInfo.CurrentPlayers, SessionInfo.MaxPlayers)));
    if (HostNameText) HostNameText->SetText(FText::FromString(SessionInfo.HostName));
    if (ProtectedIndicator) ProtectedIndicator->SetText(SessionInfo.bIsPasswordProtected ? FText::FromString(TEXT("ğŸ”’")) : FText::FromString(TEXT("â€”")));
}   
//========================================================================

//==============================ì´ë²¤íŠ¸ & ì½œë°±===============================
void USFRoomListEntryWidget::OnJoinButtonClicked()
{
    if (!GameInstance) return;

    if (SessionInfo.bIsPasswordProtected)
    {
        ShowPasswordDialog(); //ë¹„ë°€ë°©ì¼ ê²½ìš° ë¹„ë°€ë²ˆí˜¸ ì…ë ¥ì°½ ë„ìš°ê¸°
    }
    else
    {
        GameInstance->JoinGameSession(SessionIndex, TEXT("")); //ì¼ë°˜ ë°© ì…ì¥
    }
}

//ì„¸ì…˜ ì…ì¥ ì½œë°±
void USFRoomListEntryWidget::OnJoinSessionComplete(bool bWasSuccessful, const FString& Message)
{
    //ì…ì¥ ì‹¤íŒ¨ ë©”ì‹œì§€ë¥¼ í‘œì‹œí•˜ê±°ë‚˜ UI ì—°ë™ ê°€ëŠ¥ (ì•ˆì“°ëŠ” ì¤‘)
}
//==========================================================================

//==============================ë¹„ë°€ë²ˆí˜¸ ì…ë ¥ì°½ í‘œì‹œ===========================
void USFRoomListEntryWidget::ShowPasswordDialog()
{
    if (!GetOwningPlayer() || !PasswordInputWidgetClass)
    {
        UE_LOG(LogTemp, Error, TEXT("[RoomListEntryWidget] PasswordInputWidgetClass is NULL or OwningPlayer is NULL"));
        return;
    }

    USFPasswordInputWidget* PW = CreateWidget<USFPasswordInputWidget>(GetOwningPlayer(), PasswordInputWidgetClass);
    if (PW)
    {
        PW->SetSessionIndex(SessionIndex);
        PW->AddToViewport(100);
    }
}
//==========================================================================
